### ISSUE TITLE
Bug with [typescript/prefer-pascal-case-enum] and string keys

### ISSUE THREAD

**Issue by alexandcote** [Shopify/eslint-plugin-shopify#516]
We tried to bump eslint-plugin-shopify to the last version (34.0.0) in our project and we faced an issue.

<details>
<summary>Stacktrace</summary>

````
TypeError: Cannot read property 'replace' of undefined
Occurred while linting /Users/alexandrecote/src/github.com/Shopify/online-store-web/app/components/RichTextEditor/types.ts:61
    at /Users/alexandrecote/src/github.com/Shopify/online-store-web/node_modules/pascal-case/node_modules/no-case/dist/index.js:36:58
    at Array.reduce (<anonymous>)
    at replace (/Users/alexandrecote/src/github.com/Shopify/online-store-web/node_modules/pascal-case/node_modules/no-case/dist/index.js:36:15)
    at Object.noCase (/Users/alexandrecote/src/github.com/Shopify/online-store-web/node_modules/pascal-case/node_modules/no-case/dist/index.js:14:26)
    at pascalCase (/Users/alexandrecote/src/github.com/Shopify/online-store-web/node_modules/pascal-case/dist/index.js:20:22)
    at isPascalCase (/Users/alexandrecote/src/github.com/Shopify/online-store-web/node_modules/eslint-plugin-shopify/lib/rules/typescript/prefer-pascal-case-enums.js:42:19)
    at TSEnumMember (/Users/alexandrecote/src/github.com/Shopify/online-store-web/node_modules/eslint-plugin-shopify/lib/rules/typescript/prefer-pascal-case-enums.js:28:14)
    at /Users/alexandrecote/src/github.com/Shopify/online-store-web/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/alexandrecote/src/github.com/Shopify/online-store-web/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
````

</details>

After some investigation, we have discovered that having a string as key in an enum cause the error. No `name` is provided [here](https://github.com/Shopify/eslint-plugin-shopify/blob/master/lib/rules/typescript/prefer-pascal-case-enums.js#L42).

You can reproduce this bug in the test environment with 
```
{
  code: `enum Example {'foo' = 'bar'}`,
  errors: [],
},
```

I suspect [this PR](https://github.com/Shopify/eslint-plugin-shopify/pull/500) introduced the bug. The old pascal-case look for `undefined` / `null` value.

You can check here. Updating the lib to the last version causes the same issue if you pass undefined.
[![Edit pascal-case tests](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-galileo-sb0cw?fontsize=14&hidenavigation=1&theme=dark)

Now the question is should ignore the check if the name is undefined or we should find why the name is set to `undefined` 🤔. This is the main reason why I didn't add the `if`.

#### Example of code in our codebase.

```ts
export enum ImageSize {
  Small = '100x100',
  '1024x1024' = '1024x1024'
}
```

**Comment by cartogram** [comment]
@alexandcote great investigation! Do you have time to submit a PR?

**Comment by alexandcote** [comment]
Do we simply want to add the undefined check like before? If yes, definitely! But if we want to validate those enum, I have no idea why we don’t have the name here.
