### ISSUE TITLE
`rules-status`/`rules-omitted` scripts don't run

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/eslint-plugin-shopify#70]
These scripts are really useful during dependency upgrades :/

```
yarn run rules-omitted
yarn run v1.3.2
$ eslint-index lib/config/all.js  --status omitted
/shopify/eslint-plugin-shopify/node_modules/eslint-index/node_modules/eslint/lib/config/config-file.js:158
        throw e;
        ^

Error: Cannot read config file: /shopify/eslint-plugin-shopify/lib/config/all.js
Error: Cannot find module './rules/prettier'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/shopify/eslint-plugin-shopify/lib/config/all.js:61:5)
```

**Comment by alexandcote** [comment]
`eslint-index` doesn't support scoped package like @typescript-eslint. I'm closing this issue.
